### ISSUE TITLE
user gets created on hosts where it should not

### ISSUE THREAD

**Issue by maxmoser1** [1it/ansible-role-users#2]
Hi Ivan,

thanks for enabling issues on the repo and thanks for your blogpost covering this role.

While reading your role tasks I was wondering why it would not create all users as soon as do_run is set, and in fact testing confirmed this issue.

Test case is using this users list:

```
    users:
      - username: 'ansibletest'
        authorized:
          - "ssh-ed25519 AAAAC3NzaC1l123"
        name: 'System Administrator'
        target_hosts:
          - "ungrouped"
        state: 'present'
      - username: 'donotcreate'
        authorized:
          - "ssh-ed25519 AAA123"
        name: 'foo'
        target_hosts:
          - "bla"
        state: 'present'
```

If you run this against an ungrouped host, you would expect that it creates the user ansibletest but in fact both get created, because "Determine target hosts" sets do_run to True and do_run is a host-wide fact.

I'm also working on a solution for the problem by adding "    - item.target_hosts in group_names" to the conditions of the task "Manage user accounts", but that does no longer support a list of target_hosts (it requires target_hosts to be just a string).

Looking forward to your input.
