### ISSUE TITLE
with_subelements don't skip users in list 

### ISSUE THREAD

**Issue by saibug** [1it/ansible-role-users#3]
Hi, 

Thanks for sharing this ansible role ! 
I have an issue, on skiping task with with_subelements  loop
Espected Results : 
Ansible should ignore the user from list , once the condition wasn't satisfied.

See below ansible config : 

```
users: 
  - username: ''TOTO'
    uid: 1000               
    authorized: ['ssh-rsa DFSDKJFDFKLVJDFVKLJ']           
    state: 'present'
    addpukey:  true
  - username: 'TITI'
     uid: 1002
     state: present
```    

The condition i have added is : 
```
 when:
    - users is iterable 
    - item.0.addpukey is defined 
```

 the error raised :
 
` "msg": "could not find 'authorized' key in iterated item '`

thanks  for answers
